name: cuacfm
description: A radio station with radioco integration.

version: 3.0.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
      sdk: flutter
  flutter_localizations:
    sdk: flutter

  verbal_expressions: ^1.0.0
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.16
  intl: ^0.19.0
  xml2json: ^6.2.7
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  http: ^1.3.0
  html: ^0.15.4
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  injector: ^4.0.0
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  flutter_widget_from_html: ^0.15.3
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  maps_launcher: ^3.0.0+1
  photo_view: ^0.15.0
  progress_indicators: ^1.0.0
  connectivity_plus: ^6.1.4
  uuid: ^4.5.1
  provider: ^6.1.5
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_performance: ^0.10.1+5
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  firebase_in_app_messaging: ^0.8.1+5
  fake_cloud_firestore: ^3.1.0
  mock_web_server: ^5.0.0-nullsafety.1
  mockito: ^5.4.6
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
      - assets/graphics/icon_info.png
      - assets/graphics/play_podcast.png
      - assets/graphics/cuac-logo.png
      - assets/graphics/empty-logo.png
      - assets/graphics/joinus.jpg
      - assets/graphics/categories/tv.jpeg
      - assets/graphics/categories/news.jpeg
      - assets/graphics/categories/sports.jpeg
      - assets/graphics/categories/society.jpeg
      - assets/graphics/categories/education.jpeg
      - assets/graphics/categories/comedy.jpeg
      - assets/graphics/categories/music.jpeg
      - assets/graphics/categories/science.jpeg
      - assets/graphics/categories/arts.jpeg
      - assets/graphics/categories/goverment.jpeg
      - assets/graphics/categories/health.jpeg
      - assets/graphics/categories/tech.jpeg
      - assets/translations/en.json
      - assets/translations/es.json
      - assets/translations/gl.json
      - assets/translations/pt.json

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Light.ttf