name: cuacfm
description: A radio station with radioco integration.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
      sdk: flutter
  flutter_localizations:
    sdk: flutter

  verbal_expressions: ^1.0.0
  audioplayers: '0.19.0'
  intl: ^0.17.0
  xml2json: ^5.2.0
  cupertino_icons: ^1.0.3
  device_info: ^2.0.2
  http: ^0.13.3
  html: ^0.15.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  injector: ^2.0.0
  animations: ^2.0.0
  cached_network_image: ^3.0.0
  flutter_html: ^2.0.0
  url_launcher: ^6.0.4
  font_awesome_flutter: ^9.0.0
  maps_launcher: ^2.0.0
  photo_view: ^0.11.1
  progress_indicators: ^1.0.0
  connectivity: ^3.0.6
  uuid: ^3.0.1
  provider: ^5.0.0
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  firebase_performance: ^0.7.0+3
  firebase_crashlytics: ^2.0.4
  firebase_analytics: ^8.1.0
  firebase_in_app_messaging: ^0.5.0+4
  mock_web_server: ^4.1.1
  mockito: ^4.1.1
  countdown: ^0.1.0
  ozzie: ^2.2.3

dependency_overrides:
  convert: ^3.0.0
  crypto: ^3.0.0
  archive: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
      - assets/graphics/icon_info.png
      - assets/graphics/play_podcast.png
      - assets/graphics/cuac-logo.png
      - assets/graphics/empty-logo.png
      - assets/graphics/categories/tv.jpeg
      - assets/graphics/categories/news.jpeg
      - assets/graphics/categories/sports.jpeg
      - assets/graphics/categories/society.jpeg
      - assets/graphics/categories/education.jpeg
      - assets/graphics/categories/comedy.jpeg
      - assets/graphics/categories/music.jpeg
      - assets/graphics/categories/science.jpeg
      - assets/graphics/categories/arts.jpeg
      - assets/graphics/categories/goverment.jpeg
      - assets/graphics/categories/health.jpeg
      - assets/graphics/categories/tech.jpeg
      - assets/graphics/faster.jpg
      - assets/graphics/sleep.jpg
      - assets/translations/en.json
      - assets/translations/es.json
      - assets/translations/gl.json
      - assets/translations/pt.json

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Light.ttf