name: cuacfm
description: A radio station with radioco integration.

version: 1.0.0+1

environment:
  sdk: "2.15.1"

dependencies:
  flutter:
      sdk: flutter
  flutter_localizations:
    sdk: flutter

  verbal_expressions: ^1.0.0
  audioplayers: ^0.20.1
  intl: ^0.17.0
  xml2json: ^5.3.2
  cupertino_icons: ^1.0.4
  device_info: ^2.0.3
  http: ^0.13.4
  html: ^0.15.0
  share: ^2.0.4
  shared_preferences: ^2.0.11
  injector: ^2.0.0
  animations: ^2.0.2
  cached_network_image: ^3.2.0
  flutter_html: ^3.0.0-alpha.2
  url_launcher: ^6.0.17
  font_awesome_flutter: ^9.2.0
  maps_launcher: ^2.0.1
  photo_view: ^0.13.0
  progress_indicators: ^1.0.0
  connectivity: ^3.0.6
  uuid: ^3.0.5
  provider: ^6.0.2
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  firebase_performance: ^0.8.0+4
  firebase_crashlytics: ^2.4.5
  firebase_analytics: ^9.0.5
  firebase_in_app_messaging: ^0.6.0+6
  mock_web_server: ^5.0.0-nullsafety.1
  mockito: ^5.0.17
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
      - assets/graphics/icon_info.png
      - assets/graphics/play_podcast.png
      - assets/graphics/cuac-logo.png
      - assets/graphics/empty-logo.png
      - assets/graphics/joinus.jpg
      - assets/graphics/categories/tv.jpeg
      - assets/graphics/categories/news.jpeg
      - assets/graphics/categories/sports.jpeg
      - assets/graphics/categories/society.jpeg
      - assets/graphics/categories/education.jpeg
      - assets/graphics/categories/comedy.jpeg
      - assets/graphics/categories/music.jpeg
      - assets/graphics/categories/science.jpeg
      - assets/graphics/categories/arts.jpeg
      - assets/graphics/categories/goverment.jpeg
      - assets/graphics/categories/health.jpeg
      - assets/graphics/categories/tech.jpeg
      - assets/translations/en.json
      - assets/translations/es.json
      - assets/translations/gl.json
      - assets/translations/pt.json

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Light.ttf